In [1]:
import pandas as pd


In [3]:
df = pd.read_csv("../data/training_topics.tsv", sep='\t')
df

label  gender  profession ideology_binary ideology_multiclass  \
0      @user1    male  politician            left       moderate_left   
1     @user10    male  journalist           right      moderate_right   
2    @user100  female  politician            left       moderate_left   
3    @user105    male  politician            left       moderate_left   
4    @user106    male  politician           right      moderate_right   
..        ...     ...         ...             ...                 ...   
309   @user95    male  politician            left       moderate_left   
310   @user96  female  politician           right      moderate_right   
311   @user97  female  politician            left       moderate_left   
312   @user98    male  journalist            left                left   
313   @user99    male  politician            left                left   

            1         2         3         4         5  ...        11  \
0    0.206275  0.054648  0.207477  0.242832  0.223965  ...  0.000000   
1    0.000000  0.051442  0.087411  0.274578  0.332033  ...  0.047834   
2    0.207664  0.130034  0.052618  0.065578  0.314128  ...  0.083108   
3    0.322386  0.024264  0.096203  0.135699  0.000000  ...  0.225462   
4    0.102616  0.105850  0.049250  0.176024  0.345154  ...  0.383902   
..        ...       ...       ...       ...       ...  ...       ...   
309  0.237300  0.157559  0.072125  0.111087  0.105769  ...  0.160418   
310  0.042222  0.078592  0.151973  0.160658  0.660191  ...  0.044761   
311  0.441276  0.325031  0.117688  0.138318  0.017958  ...  0.433580   
312  0.091473  0.000000  0.126106  0.028968  0.492290  ...  0.096791   
313  0.053392  0.022367  0.128885  0.158040  0.000000  ...  0.195024   

           12        13        14        15        16        17        18  \
0    0.604767  0.130542  0.056920  0.419203  0.060554  0.042944  0.049037   
1    0.128270  0.031212  0.180006  0.219689  0.027097  0.171107  0.100799   
2    0.516876  0.114909  0.269394  0.226985  0.303760  0.000000  0.094920   
3    0.206301  0.092355  0.096149  0.097779  0.219983  0.089442  0.076374   
4    0.162957  0.084551  0.104914  0.147778  0.025921  0.172898  0.048663   
..        ...       ...       ...       ...       ...       ...       ...   
309  0.074717  0.023810  0.105182  0.321157  0.359611  0.066540  0.049117   
310  0.168462  0.000000  0.306218  0.655728  0.193180  0.000000  0.022046   
311  0.072927  0.000000  0.026376  0.073836  0.441490  0.134577  0.085834   
312  0.068304  0.107079  0.560888  0.281286  0.100746  0.087571  0.072205   
313  0.020416  0.791561  0.115416  0.303733  0.000000  0.066994  0.126346   

           19        20  
0    0.296865  0.037893  
1    0.029048  0.322573  
2    0.049865  0.099142  
3    0.633762  0.075038  
4    0.083670  0.108762  
..        ...       ...  
309  0.258545  0.267149  
310  0.000000  0.348120  
311  0.144251  0.104567  
312  0.105342  0.021245  
313  0.172737  0.023917  

[314 rows x 25 columns]

In [8]:
Xtrain = df.iloc[:,5:].to_numpy()

In [9]:
from sklearn.model_selection import train_test_split

In [16]:
from tqdm import tqdm

In [27]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, f1_score


scores = []
for i in tqdm(range(100)):
    xtrain, xtest, ytrain, ytest = train_test_split(Xtrain, df.ideology_multiclass)
    m = SVC(class_weight='balanced')

    m.fit(xtrain, ytrain)
    predictions = m.predict(xtest)
    cm =confusion_matrix(ytest, predictions)
    cr = classification_report(ytest, predictions, zero_division = 0, output_dict=True
                              )
    score = cr['weighted avg']['f1-score']
    scores.append(score)
print(cm)
print(cr)
#print()


100%|██████████| 100/100 [00:00<00:00, 149.44it/s]

[[14  2  1  4]
 [ 2 19  2  2]
 [ 2  8  8  6]
 [ 3  3  0  3]]
{'left': {'precision': 0.6666666666666666, 'recall': 0.6666666666666666, 'f1-score': 0.6666666666666666, 'support': 21}, 'moderate_left': {'precision': 0.59375, 'recall': 0.76, 'f1-score': 0.6666666666666666, 'support': 25}, 'moderate_right': {'precision': 0.7272727272727273, 'recall': 0.3333333333333333, 'f1-score': 0.4571428571428572, 'support': 24}, 'right': {'precision': 0.2, 'recall': 0.3333333333333333, 'f1-score': 0.25, 'support': 9}, 'accuracy': 0.5569620253164557, 'macro avg': {'precision': 0.5469223484848484, 'recall': 0.5233333333333333, 'f1-score': 0.5101190476190476, 'support': 79}, 'weighted avg': {'precision': 0.6088391829689298, 'recall': 0.5569620253164557, 'f1-score': 0.5555455093429776, 'support': 79}}


In [18]:
import numpy as np

In [22]:
'gender', np.mean(scores), '+/-', np.std(scores)

('gender', 0.6611775189797916, '+/-', 0.047955783134448426)

In [24]:
'profession', np.mean(scores), '+/-', np.std(scores)

('profession', 0.8738187657485981, '+/-', 0.031143091896702432)

In [26]:
'ideology_binary', np.mean(scores), '+/-', np.std(scores)

('ideology_binary', 0.8055136349621734, '+/-', 0.04074404397697279)

In [28]:
'ideology_multi', np.mean(scores), '+/-', np.std(scores)

('ideology_multi', 0.6223828528326054, '+/-', 0.04505287664056626)